### ISSUE TITLE
[nextgen-editor] Raw Markdown seems to be displayed instead of WYSIWYM for Font Awesome Icons in Headers

### ISSUE THREAD

**Issue by paulhibbitts** [getgrav/grav-premium-issues#32] opened 2021-01-30 00:15 UTC
I've noticed that raw Markdown (i.e. ##) gets displayed instead of a larger font size for Headers using the Font Awesome shortcode:

<img width="1440" alt="2021-01-29_16-11-10" src="https://user-images.githubusercontent.com/1812771/106339947-fe64fd80-624c-11eb-9309-974f8c210792.png">

This is remains even after a Save in the NextGen Editor... here is the raw Markdown that gets saved:

`## [fa="calendar-o" /][Week 1 (Jan 11 - 17)](../home/week-01)`

Please let me know if I can provide any more info or if I am doing something uncorrectly.

Thank you!
Paul

**Comment by paulhibbitts** [comment] 2021-02-18 18:04
Hi @w00fz , good news this issue has been solved🙂 After some more digging I found that the syntax was a bit off for the NextGen Editor but still worked in the Standard Editor.

Orginal syntax:
`## [fa="calendar-o" /][Week 1 (Jan 11 - 17)](../home/week-01)`

Fixed syntax:
`## [[fa="calendar-o"][/fa]Week 1 (Jan 11 - 17)](../home/week-01)`

I will close this issue now, sorry for not catching this earlier!

**Comment by paulhibbitts** [comment] 2021-03-22 17:53
I am re-opening this issue as I am unable to get the following syntax to work - am I doing something wrong here?

`## [fa="calendar-o"][/fa]Week 6 (Jun 13 - 19)`

NextGen Editor display:
![CleanShot 2021-03-22 at 10 53 11](https://user-images.githubusercontent.com/1812771/112035488-d7180780-8afc-11eb-9db7-d0c2420d8f4b.png)

**Comment by w00fz** [comment] 2021-04-19 07:20
This is fixed now, will release a new version in the morning.

Cheers,

**Closed by w00fz** 2021-04-19 07:20 UTC
Labels: nextgen-editor

**Comment by paulhibbitts** [comment] 2021-04-19 17:31
Of that's great news @w00fz , thank you!

**Comment by w00fz** [comment] 2021-04-19 20:26
v1.0.7 is out now @paulhibbitts

**Comment by paulhibbitts** [comment] 2021-04-19 20:39
Thanks @w00fz , but I've got mixed results...

<img width="1200" alt="2021-04-19_13-37-28" src="https://user-images.githubusercontent.com/1812771/115300198-86ec8f00-a114-11eb-9f48-52509ed02572.png">

Any ideas why this is happening? Here is my page Markdown:

```
## [fa="calendar-o"][/fa]Module 1 (May 9 - 15)
**[What is usability and user experience design?](https://canvas.sfu.ca/courses/55288/modules/items/1561554)**  
[fa="desktop"][/fa][plugin:page-inject](../presentations/module-01?template=partials/presentation_iframelinkonly)
[fa="book"][/fa][Usability 101: Introduction to Usability](https://www.nngroup.com/articles/usability-101-introduction-to-usability/)  

## [fa="calendar-o"][/fa]Module 2 (May 16 - 22)
**[What does a holistic user experience design process look like?](https://canvas.sfu.ca/courses/55288/modules/items/1561555)**  
[fa="pencil"][/fa][Course Reflection Log](https://canvas.sfu.ca/courses/55288/assignments) due Aug 3rd  
[fa="desktop"][/fa][plugin:page-inject](../presentations/module-02?template=partials/presentation_iframelinkonly)
[fa="book"][/fa][The Evolution of UX Process Methodology](https://uxplanet.org/the-evolution-of-ux-process-methodology-47f52557178b)  
```

Thanks!
Paul

**Comment by w00fz** [comment] 2021-04-19 20:41
For those that won't convert, remove the white space between the `#` and `[fa` and add it back, you should see it getting converted. Alternatively, remove the `## ` and re make it H2 and save. 

This was part of the issue with blank spaces between headers and shortcodes, so it does need to be adjusted if it's not automatically doing it.

**Comment by w00fz** [comment] 2021-04-19 21:04
> Anything else I could try?

Yes, the next release v1.0.8 after I have re-released... I did an oopsie! :)

**Comment by w00fz** [comment] 2021-04-19 21:13
The fix was getting applied only once because my regex was wrong. This is sorted now and you should see expected behavior with v1.0.8 which I just released. Should be out soon.

Sorry about that, thanks for catching this!

**Comment by paulhibbitts** [comment] 2021-04-19 21:36
Thanks so much @w00fz , 👍🏼👍🏼👍🏼

<img width="1200" alt="2021-04-19_14-34-22" src="https://user-images.githubusercontent.com/1812771/115306417-a2f42e80-a11c-11eb-878e-dede749ccc58.png">
