### ISSUE TITLE
[typhoon] When copying a module page, it reverts to Blog

### ISSUE THREAD

**Issue by setuix** [getgrav/grav-premium-issues#467] opened 2024-12-18 08:31 UTC
When I try to copy a module page because I want the same settings on the duplicated module pages, most of the time it automatically sets as Blog and I'm not able to select Gallery.

**Comment by rhukster** [comment] 2024-12-18 11:36
Typically it will change the type to the same type as the other items in the folder you are copying it to.  it's a grav feature to save time, but it may not always work as intended.  You should be able to simply change the template type back in the admin.

**Comment by rhukster** [comment] 2024-12-18 11:37
BTW, as this is not an issue specific to Typhoon, i'm going to close it here.

**Closed by rhukster** 2024-12-18 11:37 UTC
Labels: typhoon

**Comment by setuix** [comment] 2024-12-18 11:42
<img width="1295" alt="Screenshot 2024-12-18 at 7 40 08 PM" src="https://github.com/user-attachments/assets/472b2d9d-d931-47df-9de3-5e101d0afa22" />

The folder only contains gallery modules, after it auto selects blog, I can't even change it to gallery. if I'm doing something wrong I would appreciate if you can point me in the right direction.
