### ISSUE TITLE
NextGen: Possible issue with sub-sequential inline Shortcodes

### ISSUE THREAD

**Issue by paulhibbitts** [getgrav/grav-premium-issues#25] opened 2021-01-25 21:42 UTC
I've noticed that upon Save some of my inline Shortcodes seem to no longer display in NextGen as the second shortcode seems to be appended with the first shortcode end marker.

Initial display in NextGen:
<img width="1440" alt="2021-01-25_13-33-48" src="https://user-images.githubusercontent.com/1812771/105769506-c4c18900-5f12-11eb-9166-d08f3a60a127.png">

Markdown source:
<img width="1440" alt="2021-01-25_13-36-53" src="https://user-images.githubusercontent.com/1812771/105769539-cee38780-5f12-11eb-93d1-ed37af99f585.png">

But after saving in NextGen this no longer renders correctly:
<img width="1440" alt="2021-01-25_13-34-37" src="https://user-images.githubusercontent.com/1812771/105769561-d6a32c00-5f12-11eb-9f6d-5ef3ebb82233.png">

Any ideas? Am I using an incorrect syntax?

Please let me know if any more info is helpful etc.
Paul
ps - BTW, I am working on an online presentation including a demo of the NextGen Editor for my course sites, and that is why I am finding a few issues recently🙂

**Comment by w00fz** [comment] 2021-01-25 21:47
Seems to be the `[badge]` shortcode potentially getting parsed wrong because i can see the `[fa]` shortcode is getting closed twice.

Try closing your badge with `[badge ... /]` instead of `[badge ...][/badge]`, try doing the same for `[fa /]`, try using self-closing tags.

**Comment by paulhibbitts** [comment] 2021-01-25 21:55
Thanks very much @w00fz , I tried this change:

`[fa="keyboard-o" /][One-minute Summaries for Week 1](https://canvas.sfu.ca/courses/59869/assignments) [badge label="Thu Jan 14th 11:59pm PST" url="https://www.timeanddate.com/worldclock/fixedtime.html?msg=CMPT-363+One-minute+Summaries+for+Week+2+Due+Date&iso=20210114T235900&p1=256" /]  `

and upon just loading the page NextGen displays this still:

`[fa="keyboard-o" /]One-minute Summaries for Week 1 [badge label="Thu Jan 14th 11:59pm PST" url="https://www.timeanddate.com/worldclock/fixedtime.html?msg=CMPT-363+One-minute+Summaries+for+Week+2+Due+Date&iso=20210114T235900&p1=256" ][/fa]  `

If helpful I can share either a Grav site or user folder etc.

Thanks,
Paul

**Comment by w00fz** [comment] 2021-01-25 22:23
if you remove the badge or perhaps try changing the label / url to 1 character, does it save right?
I think something with the Badge shortcode might be interfering.

**Comment by paulhibbitts** [comment] 2021-01-25 22:31
Ok, removing the Badge stuff entirely everything worked, but when changing the labe/url to a char I still got:
`[fa="keyboard-o" /]One-minute Summaries for Week 1 [badge label="T" url="h" ][/fa]  `

As a test, I've next tried two subsequent FontAwesome shortcodes:
`[fa="keyboard-o" /][One-minute Summaries for Week 1](https://canvas.sfu.ca/courses/59869/assignments)[fa="keyboard-o" /][One-minute Summaries for Week 1](https://canvas.sfu.ca/courses/59869/assignments)`

and this rendered in NextGen as:
<img width="711" alt="2021-01-25_14-29-44" src="https://user-images.githubusercontent.com/1812771/105774258-ee31e300-5f19-11eb-8567-338a0db04d9a.png">

And two subsequent Badge shortcodes:
<img width="965" alt="2021-01-25_14-30-25" src="https://user-images.githubusercontent.com/1812771/105774293-f68a1e00-5f19-11eb-831c-f9589bdbf448.png">

Can you repeat my results with two subsequent Fontawesome shortcodes?
Paul

**Comment by w00fz** [comment] 2021-01-25 22:48
I do not have your badge shortcode i don't think, sounds like that is what's throwing off the parsing though. Can you share the badge shortcode for nextgen?

**Comment by paulhibbitts** [comment] 2021-01-25 22:52
Sure thing, but did you also see above that two Fontawesome shortcodes in a row without the Badge shortcode on the same page also seems to have issues?

Here is my Badge shortcode:
https://github.com/hibbitts-design/grav-theme-bootstrap4-open-matter/blob/master/nextgen-editor/shortcodes/badge.js

Also in my released Bootstrap4 Open Matter theme. Please let me know if I can be of any more help.

**Comment by w00fz** [comment] 2021-01-25 22:57
Oh sorry I missed that comment, yes I can reproduce it with even just 2 fa on the same line. Will investigate that

**Comment by w00fz** [comment] 2021-01-26 01:22
Hi @paulhibbitts , I’m able to recreate this issue and found out it’s a regression in the shortcode plugin. When we worked on fixing having urls in the attributes for shortcodes back in December, this case ceased to function properly.

I am working on finding a regexp that is compatible with both cases.

Thanks for bringing this up.

**Comment by paulhibbitts** [comment] 2021-01-26 01:29
Awesome @w00fz , thanks again for looking into it!

**Comment by w00fz** [comment] 2021-01-26 04:43
Hi @paulhibbitts, I think this is what you were looking for?

<img width="1086" alt="CleanShot 2021-01-25 at 20 40 23@2x" src="https://user-images.githubusercontent.com/11734/105801243-93b27a00-5f4d-11eb-970c-9b8c23b51718.png">

<img width="500" alt="CleanShot 2021-01-25 at 20 39 36@2x" src="https://user-images.githubusercontent.com/11734/105801191-78476f00-5f4d-11eb-8771-f77b939e496a.png">

I pushed the changes in https://github.com/getgrav/grav-plugin-shortcode-core/commit/5e1bf0b46bf03354b22db6858cc8ff3954882531 

Let me know if you can test the `develop` zip to make sure everything runs smoothly and as expected now, before I officially release the new version.

Cheers!

**Comment by paulhibbitts** [comment] 2021-01-26 16:05
Thanks so much @w00fz , that is exactly what I was looking for🙂 Your developement fix works perfectly, even on my complete Schedule page! Thanks again.

**Comment by w00fz** [comment] 2021-01-26 16:30
Sweet, I'll get shortocode-core released later today

**Comment by w00fz** [comment] 2021-01-26 18:19
Shortcode-core v5.0.4 is released, should be available soon in GPM.

Thanks!

**Closed by w00fz** 2021-01-26 18:19 UTC
Labels: bug, nextgen-editor
