### ISSUE TITLE
[typhoon 1.0.8] Social Link Being Duplicated

### ISSUE THREAD

**Issue by Umbyology** [getgrav/grav-premium-issues#31] opened 2021-01-29 21:10 UTC
Also, I only have one social link on my site using the Premium theme, but somehow it keeps adding a second social link; perhaps when I change something else and resave those options. See attachments.

<img width="1644" alt="Screen Shot 2021-01-29 at 3 03 36 PM" src="https://user-images.githubusercontent.com/22547499/106327591-053b4280-6244-11eb-94d4-a7502e7c926b.png">

<img width="1543" alt="Screen Shot 2021-01-29 at 3 02 53 PM" src="https://user-images.githubusercontent.com/22547499/106327586-01a7bb80-6244-11eb-8546-24f02790ce39.png">

**Comment by rhukster** [comment] 2021-01-29 21:19
I can't replicate this.  I have one, I make an edit to it and save, and I still have one entry just modified.

What version of Grav/Admin are you on?

**Comment by Umbyology** [comment] 2021-01-29 21:24
It doesn't do it right away. I'm working on the site now. Saving this-n-that, adding a few plugins, so it must be doing it as I'm working and saving. I just happen to notice it, but it has done this on me now three times :)

Everything is updated. No Betas. Mostly official plugins and the new premium stuff.

**Comment by Umbyology** [comment] 2021-01-29 21:26
Just did it again on me. LOL ... I'll try to determine what is triggering it and let you know.

**Comment by rhukster** [comment] 2021-01-29 21:27
Please let us know if its caused by a plugin or something, because we use this "List" field all the time and have never run into this issue.

**Comment by Umbyology** [comment] 2021-01-30 00:51
Well, in the process of upgrading my site with all your new premium plugins (love'em), I needed to do some customizing and had to create a child theme for Inheritance reasons. Works great! ... but I've not seen the bug now. I'd say close this ticket. If I see it again, I will come back here and re-post.

THX Andy!

**Comment by w00fz** [comment] 2021-01-30 02:45
Thanks for the support!

**Comment by Umbyology** [comment] 2021-02-01 22:57
It's back ... with a vengeance. So, I had to temporarily revert back to the base-theme (a separate issue) and now I cannot delete these social links; when I do and return to the page there they sit. How is that even possible? ... one of the links belongs to GRAV. If I delete one, it will return. If I delete both, they both return as soon.

I've tried wiping the cache, no change.

<img width="1605" alt="Screen Shot 2021-02-01 at 4 51 40 PM" src="https://user-images.githubusercontent.com/22547499/106528420-5babb980-64ae-11eb-845e-90a5ed001b28.png">

**Comment by Umbyology** [comment] 2021-02-01 23:02
Actually I don't even need to refresh the page, I just noticed they return when I Save and the page refreshes itself.

**Comment by Umbyology** [comment] 2021-02-02 00:42
So, I reinstalled GRAV from scratch; fresh install v1.7.4, only saving my User directory. I then restored my user directory and re-activated my Premium products.

The issue still persists. I've tried everything I can think of at this point. However, since my Child-Theme and Inheritance is working again (different issue) I'm no longer using the Base-Theme and the issue is not showing on the front end. So, this issue is not an issue .... right now anyway.

THX!

**Comment by Umbyology** [comment] 2021-02-02 04:03
Well damn. Sorry for the roller coaster here, but this issue is not just related to the Social LInks. It is affecting all theme settings, including per-page-settings; on both the child-theme and base-theme.

At this point, I cannot make any changes to theme settings at all because they will not save. I don't get any errors; I click save; it simply refreshes with no saved changes.

I set up the child-theme using the instructions under GetGrav > Learn ... but these instructions were for the Quark theme, so I made the changes accordingly. Inheritance seems to be working fine. However, does this code placed into the child-theme's YAML still apply for Typhoon ...

`streams:
  schemes:
    theme:
      type: ReadOnlyStream
      prefixes:
        '': [user/themes/mytheme, user/themes/typhoon]`

I'm asking because it says "ReadOnlyStream" ... could that be why it is not saving any theme settings?

**Comment by rhukster** [comment] 2021-02-02 04:18
Well, that's odd.. i can replicate things not saving with page-level overrides like Hero settings.  Something must of changed recently.  I'll get back to you.

**Comment by rhukster** [comment] 2021-02-02 04:40
Ok, turns out this was not a Typhoon thing, but a Grav 1.7.4 thing.  I found the bad commit, reverted and re-released as 1.7.5, regenerating the GPM now.

**Comment by Umbyology** [comment] 2021-02-02 17:24
Cool, I'll do an update and let you know.

**Comment by rhukster** [comment] 2021-02-02 17:31
Btw if you were working in one page and still having trouble saving you might need to go into expert mode and remove the weird data that might have been stored in the front matter. It will make it look like it still not saving. I had this in one page but not another. Once it’s gone all will be well.

**Comment by Umbyology** [comment] 2021-02-02 17:39
Roger that. Yep. This seems to have solved the per page issue with saving settings. THX!

However, it did not solve the original "Social Link Being Duplicated" problem, I was hoping they might be related. However, and again, since I use a child-theme, the issue doesn't show. Very odd ... see attachment.

I've done a complete clean-install of GRAV. But I'll let you decide if you want to close this ticket for now. If I find the culprit I'll let you know.

**Comment by rhukster** [comment] 2021-02-03 18:21
I wish I could recreate this but I can't!  I'm not sure why you are getting that one added.  Could you show me what the contents of your frontmatter looks like via the EXPERT mode? I  think it might have some corruption in there.

**Comment by Umbyology** [comment] 2021-02-04 01:55
So, I wasn't sure what was causing the 2nd social link to keep returning after I delete it. But now I can reproduce it every time through the following process...

* Create a social link, click save.
* From Admin Quicklinks, Clear Cache.
* Click Dashboard, wait for the page to load.
* Click Themes; Click Typhoon; Click Content Tab.
* Scroll down, you should now see two Social Links.

Since I have completed a fresh install of GRAV, then if you cannot reproduce the issue it must be a conflict with a plugin.

In regards to your question ... by "EXPERT mode" which theme file do you mean?

**Comment by Umbyology** [comment] 2021-02-04 01:58
Something of interest with the process I outlined previously ... If I don't "Clear Cache" it doesn't create the 2nd social link.

**Comment by rhukster** [comment] 2021-02-04 02:02
I tried your steps but i still don't get a second social link added. :(

also ignore my "expert mode" comment, was thinking this was a page blueprint for some reason.  Please just paste the contents of your `user/config/themes/typhoon.yaml` (or whatever your child theme is called)

**Comment by Umbyology** [comment] 2021-02-04 02:10
`streams:
  schemes:
    theme:
      type: ReadOnlyStream
      prefixes:
        '': [user/themes/mytheme, user/themes/typhoon]
enabled: true
production: true
append_site_title: true
custom_logo:
  user/assets/typhoon/umbyology.logo.400.80.144.png:
    name: umbyology.logo.400.80.144.png
    type: image/png
    size: 24649
    path: user/assets/typhoon/umbyology.logo.400.80.144.png
custom_logo_strip_svg_style: true
colors:
  text_style: 'text-gray-600 dark:text-gray-400'
  brightness_lighter: 10
  brightness_darker: 10
  primary: '#B22C00'
appearance:
  theme: dark
  selector: false
  storage: true
section_classes: 'bg-white dark:bg-gray-900 py-8 md:py-24'
wrapper_spacing: 'xl:container xl:mx-auto md:px-6 px-4'
menu:
  primary_location: header
  primary_menu_levels: 2
  mobile_nav: true
header_bar:
  background: custom
  custom_style: 'linear-gradient(180deg, rgba(0,0,0,0.9) 20%, rgba(0,0,0,0.6) 80%)'
  text: auto
  primary_menu_levels: 1
hero:
  display: true
  overlay: darker
  overlay_direction: bottom
  alignment: left
  image: 'user://images/hero/umbyology.page.1600.800.72.d20gears.jpg'
  custom: '#000000'
  padding: 'pt-32 md:pt-40 lg:pt-48 xl:pt-56 pb-16 md:pb-20 lg:pb-24 xl:pb-32'
  overlay_gradient:
    - '0.8'
    - '0.2'
footer:
  menu_enabled: true
  menu:
    -
      label: Articles
      link: /blog
    -
      label: 'My Profile'
      link: 'https://en.gravatar.com/umbyology'
    -
      label: 'My Reddit'
      link: 'https://reddit.com/r/Umbyology'
    -
      label: 'Email Me'
      link: /email
  social_enabled: true
  social:
    -
      network: github
      link: 'https://github.com/umbyology'
  copyright: "© 2021 B.A Umberger. All Rights Reserved.\r\n"
notices:
  -
    content: 'An example **critical** message that should show up on homepage only'
    enabled: false
    only_homepage: true
    type: critical
    learn_more_link: 'https://getgrav.org'
  -
    content: 'An example **note** that should appear on all pages! No link..'
    enabled: false
    only_homepage: false
    type: note
    learn_more_link: null
primary_menu_levels: 3
`

**Comment by rhukster** [comment] 2021-02-04 02:11
Ah ha! i think i found something.  I can get some weirdness when I use an extended theme (I think you are doing the same).  it's something related to the merging of the base theme's YAML and the extended theme's YAML, causing double entries to appear.

If I look at my `user/config/typhoon-copy.yaml` and the inherited `user/themes/typhoon/typhoon.yaml` I can see the merge of the first items in my config with the base config:

user/config/themes/typhoon-copy.yaml:
```yaml
  social:
    -
      network: twitter
      link: 'https://twitter.com/getgrav3'
```

user/themes/typhoon/typhoon.yaml:
```yaml
  social:
    -
      network: twitter                                          
      link: https://twitter.com/getgrav   
    -
      network: github
      link: https://github.com/getgrav
```

Result:

<img width="1058" alt="CleanShot 2021-02-03 at 19 10 17@2x" src="https://user-images.githubusercontent.com/1084697/106834887-7c614400-6653-11eb-8a8b-afc5a93bdcb1.png">

This doesn't seem to happen when I'm not inheriting, so its definitely related to the way that config is merged when inheriting.  It's kinda tricky to fix actually because changing that behavior could have unexpected results in other places.  Need to think on this.

**Comment by Umbyology** [comment] 2021-02-04 02:20
Ok, gotcha. ... Honestly, it is no big deal, for me.

If you think about it ... The only time it shows is when I have you have a child-theme, but aren't using it - relaying of the base-theme still.

Sort of a self-fulfilling issue ... lol.

**Comment by rhukster** [comment] 2021-02-08 23:00
BTW, we have a fix in the latest version of Grav that allows you to remove all entries in a list, even if there are defaults.

**Closed by rhukster** 2021-02-08 23:00 UTC
Labels: question, typhoon
