### ISSUE TITLE
[typhoon] Missing translation on 2.0.1 Admin

### ISSUE THREAD

**Issue by mouradsm** [getgrav/grav-premium-issues#99] opened 2021-05-10 23:19 UTC
After I updated the typhoon theme to 2.0.1 the admin menus and options only show the translation variables and not the text. Is there something missing or I made some mistake when updating?

![Capture](https://user-images.githubusercontent.com/2678285/117735961-f3ffbb80-b1cc-11eb-9547-b8240304f734.PNG)

**Comment by rhukster** [comment] 2021-05-10 23:31
Have you extended the theme? Or is typhoon not active?  Looks like a duplicate of: https://github.com/getgrav/grav-plugin-admin/issues/2140

**Closed** 2021-05-13 17:35 UTC
Labels: question
